### ISSUE TITLE
Replace strings with enumerations

### ISSUE THREAD

**Issue by jamesrswift** [MrGrim48/gmod_unstuck#1]
https://github.com/MrGrim48/gmod_unstuck/blob/d02dae13c027951dd3cfa9e9170a0280a2bbf6a5/lua/unstuck/sv_unstuck_table.lua#L22-L23

This will allow you to send less data while sending the same amount of information. This would also vastly increase your readability, as the name of the enumeration can explain it's effect, while "add" does not. Consider the following:

```
Unstuck.Enumerations = {
	Debug = {
		OPPERATION_AND = 1,
		NOUN_BOX = 2
	}
}
```

You can then do the following:
```
/* ... */
	net.Start( "Unstuck.Debug" )

	//net.WriteString( "add" )
	net.WriteInt( Unstuck.Enumerations.Debug.OPPERATION_ADD, 8 )

	//net.WriteString( "box" )
	net.WriteInt( Unstuck.Enumerations.Debug.NOUN_BOX , 8 )

	net.WriteVector( ply:GetPos()+minBound )
	net.WriteVector( ply:GetPos()+maxBound )
	net.WriteColor( Color(255,150,150) )
	net.Send( ply )
/* ... */
```

This will show to anyone reading your code that the two enumerations being sent work together. It also means you can send two identical values for different scenarios (eg maybe "add" could mean other things), while having them represented by different variables, allowing anyone reading the code not to have any doubt over which "add" is meant.

**Comment by MrGrim48** [comment]
Added in latest update.
