### ISSUE TITLE
Replace massive IF statements with dictionary.

### ISSUE THREAD

**Issue by jamesrswift** [MrGrim48/gmod_unstuck#2]
https://github.com/MrGrim48/gmod_unstuck/blob/d02dae13c027951dd3cfa9e9170a0280a2bbf6a5/lua/unstuck/sv_unstuck.lua#L83

This may be replaced with good use of the [table.HasValue( table tbl, any value )](http://wiki.garrysmod.com/page/table/HasValue) function.  While not effecient for large tables, it will increase the readability of the code by replacing such an if station with a dictionary search. This would also allow server owners to customize the dictionary to their own language.

Consider the following:
```
Unstuck.Configuration = {
	Command = {
		Prefix = { "!", "/" },
		String = { "stuck", "unstuck"}
	}
}
```

The following can then be achieved:

```
hook.Add("PlayerSay", "Unstuck.PlayerSay", function( ply, text )
	
	text = string.lower( text )

	// Check for the command prefix, terminate call if not present
	if ( not table.HasValue( 
		Unstuck.Configuration.Command.Prefix,
		text:sub(1, 1)
	 ) ) then return end
	
	// check for the command string, terminate call if not present
	if ( not table.HasValue( 
		Unstuck.Configuration.Command.String, 
		text:sub( 2, #text ) 
	) ) then return end

	//if ( text == "!unstuck" or text == "!stuck" or text == "/stuck" or text == "/unstuck" ) then

	/* ... */
```

**Comment by MrGrim48** [comment]
Latest update is practically copy pasted.
Moved other configurations to the Unstuck.Configuration table.
