### ISSUE TITLE
Move the data processing subroutine into a coroutine

### ISSUE THREAD

**Issue by jamesrswift** [MrGrim48/gmod_unstuck#3]
https://github.com/MrGrim48/gmod_unstuck/blob/d02dae13c027951dd3cfa9e9170a0280a2bbf6a5/lua/unstuck/sv_unstuck_func.lua#L61-L68

As suggested by [code_gs](https://facepunch.com/showthread.php?t=1577648&p=52649437&viewfull=1#post52649437)

> You could do the the actual position testing inside of a coroutine so that the server doesn't have to halt to find the player a clear position.

**Comment by MrGrim48** [comment]
Coroutines should now be implemented with the latest update.
