### ISSUE TITLE
Reduce boilerplate code

### ISSUE THREAD

**Issue by jamesrswift** [MrGrim48/gmod_unstuck#5]
https://github.com/MrGrim48/gmod_unstuck/blob/9d25d4b48b673927cdb91e0d910bf252f0a8a0cd/lua/unstuck/sh_unstuck.lua#L58-L72

Whenever a message is sent using this function, the first 3 arguments are always identical, and the 4th argument is always a predetermined string. As such, these first 3 arguments need not be sent and can instead be curried into the client side net message listener function. The 4th argument (string) can be then replaced with an enumeration that also serves as an index in a dictionary table. This will allow server owners to translate the text seen to the main language of their server through the dictionary configuration, as opposed to having to go through all the code manually. Doing this will also drastically reduce the net message's size to about 2 bytes. #

**Comment by MrGrim48** [comment]
https://github.com/MrGrim48/gmod_unstuck/commit/7caa2d3aae05e714dbea6241d3fd23618d68c4d7

Dictionary located in sh_unstuck.lua
