### ISSUE TITLE
Missing addon.json file

### ISSUE THREAD

**Issue by jamesrswift** [MrGrim48/gmod_unstuck#7]
As stated in the README.md, this addon can be installed by placing it in the server's addons folder, however this will not work if there is no addon.json file.

**Comment by haeiven** [comment]
Hi,

You don't need addon.json file ^^

**Comment by jamesrswift** [comment]
Times have changed since I last made addons :p my appologies

**Comment by MrGrim48** [comment]
It may need it if the addon was to be added to the workshop?
I will worry about it another time.
